#!/usr/bin/env python

# The sequence of triangle numbers is generated by adding the natural numbers.
# What is the value of the first triangle number to have over five hundred (not necessarily prime) divisors?

triangle = 0
i = 0
max = 1

while True:
    i += 1
    triangle += i
    d = 1; count = 0
    t = triange
    while d <= t:
        if t % d == 0:
            count += 1
        d += 1
    if count > max:
        max = count;
        print i, triangle, count
    if count > 500:
        break
